---
- name: Install Nginx Web Server
  apt:
    name=nginx
    state=latest
  notify:
    - nginx systemd

- name: Replace default site
  template:
    src=templates/nginx.conf
    dest=/etc/nginx/sites-enabled/default
  notify:
    - nginx restart

- name: Install PHP Extensions
  apt: name={{ item }} update_cache=yes state=latest
  loop: "{{ php_modules }}"

- name: Purge Apache2
  apt:
    name=apache2
    state=absent
    purge=yes

- name: Create document root
  file:
    path: "/var/www/{{ my_domain }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0755'

- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/{{ my_domain }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: "/var/www/{{ my_domain }}/wp-admin"

- name: Set ownership
  file:
    path: "/var/www/{{ my_domain }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: Set permissions for directories
  shell: "/usr/bin/find /var/www/{{ my_domain }}/ -type d -exec chmod 755 {} \\;"

- name: Set permissions for files
  shell: "/usr/bin/find /var/www/{{ my_domain }}/ -type f -exec chmod 644 {} \\;"

- name: Set up wp-config
  template:
    src: "templates/wp-config.php.j2"
    dest: "/var/www/{{ my_domain }}/wp-config.php"

- name: Restart nginx, in all cases
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: download Wordpress CLI
  command: curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o /tmp/wp-cli.phar
  args:
    creates: "/tmp/wp-cli.phar"

- name: move the binary to the final destination
  copy:
    src: "/tmp/wp-cli.phar"
    dest: "/usr/local/bin/wp"
    owner: "root"
    group: "root"
    mode: 0755
    remote_src: yes

- name: Create first site
  command: sudo -u ubuntu -- wp core install --url="www.{{ my_domain }}" --title="Experimental" --admin_user="admin" --admin_password="admin" --admin_email="admin@test.site" --skip-email
  args:
    chdir: "/var/www/{{ my_domain }}"

