---
- name: Installing Mysql  and dependencies
  package:
     name: "{{ item }}"
     state: present
     update_cache: yes
  loop:
    - mysql-server
    - mysql-client
    - python3-mysqldb
    - libmysqlclient-dev
  become: yes

- name: start and enable mysql service
  service:
     name: mysql
     state: started
     enabled: yes

- name: Remove all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: Remove the MySQL test database
  mysql_db:
    name: test
    state: absent

- name: creating db
  mysql_db:
     name: "{{ db_name }}"
     state: present

- name: creating mysql user
  mysql_user:
     name: "{{ db_user }}"
     password: "{{ db_pass }}"
     priv: "{{ db_name }}.*:ALL"
     host: '%'
     state: present

- name: Enable remote login to mysql
  lineinfile:
     path: /etc/mysql/mysql.conf.d/mysqld.cnf
     regexp: '^bind-address'
     line: 'bind-address = 0.0.0.0'
     backup: yes
  notify:
    - Restart mysql

- import_tasks: replication.yml
